Fix user-role relationship
thedevdojo/voyager pull request #2492
Opened 2018-01-15 17:32 UTC by giorgioma

The relationship User Role was broken, it was using a pivot table 'user_roles' that did not exist.
I updated the code to not use the pivot table.

I took the chance to add Voyager::modelClass in the relationship inside ./src/Model/Role.php

2018-01-15 19:55 UTC, fletch3555 requested changes

2018-01-15 19:55 UTC, fletch3555 commented on src/Traits/VoyagerUser.php
> -        return $this->belongsTo(Voyager::modelClass('Role'));
We should leave this alone.  It functions identically since you changed it to the reciprocal relation, but it's cleaner before.

2018-01-15 19:55 UTC, fletch3555 commented on src/Models/Role.php
> +        return $this->belongsTo(Voyager::modelClass('User'), 'id', 'role_id');
This should be a `hasMany()`, then you won't need the `id` and `role_id` params

2018-01-15 19:55 UTC, fletch3555 commented on src/Models/Permission.php
> +        return $this->hasMany(Voyager::modelClass('Role'));
good find, thank you.

2018-01-15 22:15 UTC, giorgioma commented
Changed as requested

2018-01-16 03:45 UTC, fletch3555 approved these changes

2018-01-16 03:56 UTC, merged