feature/voyager-config-upload-path
thedevdojo/voyager pull request #2581
Opened 2018-02-01 16:51 UTC by shakalaka

Took out in voyager configuration upload path

2018-02-14 08:15 UTC, marktopper submitted a review, later dismissed

2018-03-13 10:51 UTC, marktopper commented
Does it work for Windows systems? Or does it need to use `DIRECTORY_SEPARATOR`?

2018-03-13 18:20 UTC, fletch3555 requested changes
I think this could be better served by just letting Laravel/Voyager upload the files to a single place.  You can then either move them around manually, or choose a subfolder in the controller of a form using the file/image upload field.

I'm certainly not opposed to letting this be configurable, but I don't think the Voyager config file is the right place.  This would be better configured in the JSON "additional options" field, which allows it to be different for each BREAD type, and keeps the usage localized to the "ContentTypes" classes

2018-03-13 18:20 UTC, fletch3555 commented on src/Helpers/helperUploadPath.php
> +if (!function_exists('getUploadPath')) {
I think the helper method is too specific, and would be better served as a service class method or something.

2018-03-13 18:20 UTC, fletch3555 commented on src/Http/Controllers/ContentTypes/File.php
> +        return getUploadPath($this->slug, config('voyager.storage.path', '%slug%/%date:F%/%date:Y%/'));
As @marktopper said, you changed all of the DIRECTORY_SEPARATOR calls to literal strings, which very likely breaks OS cross-compatibility.

2018-03-13 18:20 UTC, fletch3555 commented on src/Helpers/helperUploadPath.php
> +                if ($dir === 'slug') {
I'm also not really a huge fan of the placeholder replacement.  This if/elseif/etc chain could easily get VERY long and unmanageable.

2018-03-13 18:20 UTC, fletch3555 commented on src/Helpers/helperUploadPath.php
> +        $_dirs = explode('/', $path);
Variable naming is too generic.  Also, $_ is generally reserved for PHP superglobals.

2018-04-16 20:14 UTC, marktopper commented
Closed due to inactivity

2018-04-16 20:14 UTC, closed without merging