Test widgets
thedevdojo/voyager pull request #2588
Opened 2018-02-02 10:42 UTC by marktopper

2018-02-02 15:26 UTC, fletch3555 requested changes

2018-02-02 15:26 UTC, fletch3555 commented on tests/WidgetTest.php
> +    public function testWidetsAreRegistered()
typo, should probably say "Widgets" not "Widets"

2018-02-07 10:41 UTC, marktopper commented
Thanks @fletch3555, fixed the typo

2018-02-15 15:58 UTC, fletch3555 approved these changes

2018-02-15 21:02 UTC, merged