Change redirected path after successful user login
thedevdojo/voyager pull request #2664
Opened 2018-02-14 15:38 UTC by vblinden

The user can now tell the system where it should redirect to via a config file. It defaults to the standard prefix '/admin'.

2018-02-14 23:58 UTC, akazorg commented
Nice feature.

2018-02-15 15:11 UTC, fletch3555 requested changes

2018-02-15 15:11 UTC, fletch3555 commented on src/Http/Controllers/VoyagerAuthController.php
> +        return config('voyager.user.redirect');
Can you give the config call a default value?  Without it, this will blow up if the config isn't there (anyone that upgrades from an older version)

2018-02-16 10:50 UTC, ArtemMolotov commented
@vblinden, Can you set `route('voyager.dashboard')` as default value?

2018-02-16 15:22 UTC, fletch3555 approved these changes

2018-02-16 15:46 UTC, merged