Fixes #2075 and #1949
thedevdojo/voyager pull request #2677
Opened 2018-02-16 10:49 UTC by vblinden

When deleting a menu, canceling it and opening another menu again. The action has two id's like this: .../2/1. This pull requests fixes that.

2018-02-16 14:55 UTC, fletch3555 commented
Can you make sure this applies to all types? This behavior likely exists in all Voyager BREAD views

2018-02-16 14:58 UTC, vblinden commented
@fletch3555 Sure, I will check every delete modal and update the PR.

2018-02-16 15:19 UTC, fletch3555 commented
This is essentially the same as #2670.  One uses `__id`, and the other uses the index route and appends the id.  Can you make them function the same (I prefer using the correct route, not assuming the delete route is the same as appending the id to the index route).

2018-02-16 21:39 UTC, vblinden commented
Fixed all the other instances I could find. Some have different routes and so we have to append the id to the end and not replace the `__id`.

2018-02-16 21:58 UTC, fletch3555 requested changes

2018-02-16 21:58 UTC, fletch3555 commented on resources/views/bread/browse.blade.php
> +            $('#delete_form')[0].action = '{{ route('voyager.'.$dataType->slug.'.index') }}' + '/' + $(this).data('id');
Can you make this one use the `__[x]` placeholder like the rest?

2018-02-16 21:58 UTC, fletch3555 commented on resources/views/menus/browse.blade.php
> +            $('#delete_form')[0].action = '{{ route('voyager.'.$dataType->slug.'.index') }}' + '/' + $(this).data('id');
This one too.

2018-02-16 22:00 UTC, fletch3555 commented
Sorry, just saw your comment about needing to append.  What do you mean they "have different routes"?  If it's an issue where some are ".delete" and some are ".destroy", then I think that's a different issue that should be changed as well.

2018-02-16 22:02 UTC, vblinden commented
Yes, we generate all the routes for the datatypes. But we set the routes for database and setting our self. So they differ from the generated ones. I could make that a different pull request, where we make the routes the same?

2018-02-16 22:20 UTC, fletch3555 commented
Yes, please make them all the same (bread ones should be resource routes, so they're all `destroy`). We did this same thing a while back, so we must've just missed some.  Go ahead and test that under the 1.x-dev branch to make sure it wasn't just merged there for some reason

2018-02-16 22:21 UTC, fletch3555 commented
Yes, please make them all the same (bread ones should be resource routes, so they're all `destroy`). We did this same thing a while back, so we must've just missed some.  Go ahead and test that under the 1.x-dev branch to make sure it wasn't just merged there for some reason

2018-02-16 23:03 UTC, vblinden commented
I made them all append (so we have some unity, like the resource routes). Are there any other delete modals that I missed?

2018-03-01 16:05 UTC, fletch3555 approved these changes

2018-03-01 16:22 UTC, merged

2018-03-25 01:05 UTC, emptynick commented
Something went wrong [here](https://github.com/the-control-group/voyager/pull/2677/files#diff-52e64b52374bf2d87cd76ecbb043ca63R109)
You set the form-action to `database.destroy` when someone trys to delete a menu.
Good thing is that `table` is not defined, so this just doesn't work.
Otherwise it would just delete a whole table

2018-03-25 17:55 UTC, vblinden commented
Wow! Good catch! Should I make a pr to fix this?

2018-03-25 17:57 UTC, emptynick commented
No, I did already: https://github.com/the-control-group/voyager/pull/2892