Add the ability to add custom actions buttons
thedevdojo/voyager pull request #2678
Opened 2018-02-16 14:48 UTC by vblinden

Hello everyone,

At the moment there is no way to define a custom action in the BREAD browse overview. Only the default view, delete and edit actions are available. With this pull request it is possible for someone to add a for example a download action to a certain datatype.

The way you would do this is create a new class `DownloadAction` and extend it with the `AbstractAction`. You can give it a title, icon and set the attributes. You can also specify which on which DataType you want too show the action and define custom routes for each datatype.

Let me know what you guys think! Feedback is appreciated!

2018-02-16 15:07 UTC, fletch3555 requested changes

2018-02-16 15:07 UTC, fletch3555 commented on resources/views/bread/browse.blade.php
> +                                                @php $action = new $action($dataType, $data); @endphp
Can we move the rendering of this into a view partial? Then this code would just be this: https://laravel.com/docs/5.5/blade#rendering-views-for-collections

2018-02-16 15:08 UTC, fletch3555 commented
This will need to go in `1.x-dev`.  Make sure you talk to @emptynick about his BREAD redesign so this can get implemented with it

2018-02-16 21:50 UTC, vblinden commented
We can't use the `@each` blade helper cause that doesn't inherit the variables of the parent view and we need the `$dataType` and `$data`. So now we use the `@include` blade helper with a different view.

2018-02-16 21:55 UTC, fletch3555 commented
Thanks.  Can you resolve the conflict as well?  Just pull 1.x-dev into your branch, discard the conflicted change, keeping your version (with the @foreach and @include), then update your Action classes to use the `voyager::` prefix in your `getTitle()` methods

2018-03-14 02:59 UTC, fletch3555 approved these changes

2018-03-14 03:18 UTC, merged

2018-06-08 14:10 UTC, alexandrekadri commented
hi, I think could be usefull if add like BREAD-EX permissions. For each BREAD  exists add permissions  "Export".

2018-06-08 14:35 UTC, fletch3555 commented
This PR was merged ~3 months ago.  Bugs and Feature requests should be reported as their own issues here, not on closed issues/PRs.