Re #2287: Cover Image Upload Field Accepts Non-Image Filetypes
thedevdojo/voyager pull request #2733
Opened 2018-02-25 23:52 UTC by mattrabe

- Add `accept="image/*"` as recommended by @envision

2018-02-26 14:37 UTC, fletch3555 requested changes
What about the "multiple images" field?

2018-02-26 17:27 UTC, mattrabe commented
@fletch3555 Roger that, will add...

2018-02-26 17:52 UTC, mattrabe commented
@fletch3555 Okay - added it to multiple_images as well

2018-02-28 12:05 UTC, marktopper approved these changes

2018-02-28 13:13 UTC, fletch3555 approved these changes

2018-02-28 13:13 UTC, merged