Add resize option to thumbnails
thedevdojo/voyager pull request #2876
Opened 2018-03-22 15:04 UTC by reficul

There are no way to resize an image to make a thumbnail, you can only scale or crop original image.
With this PR I add the "resize" option also to thumbs.

usage:
```
    "thumbnails": [
        {
            "name": "resizedthumb",
            "resize": {
                "width": null,
                "height": "250"
            }
        }
    ]
```

2018-03-25 10:56 UTC, emptynick requested changes

2018-03-25 10:56 UTC, emptynick commented on src/Http/Controllers/Controller.php
> +                                } elseif (isset($options->thumbnails) && isset($thumbnails->resize) && (isset($thumbnails->resize->width) || isset($thumbnails->resize->height))) {
Theres already a check if `$options->thumbnails` is set on [Line 268](https://github.com/reficul/voyager/blob/8433b9e82dc495dc61be6e9a732afba72e685886/src/Http/Controllers/Controller.php#L268)
I know, its the same for #293 maybe you can remove that check also!

2018-03-25 10:56 UTC, emptynick commented on src/Http/Controllers/Controller.php
> +                            } elseif (isset($options->thumbnails) && isset($thumbnails->resize) && (isset($thumbnails->resize->width) || isset($thumbnails->resize->height))) {
Same here, see [Line 428](https://github.com/reficul/voyager/blob/8433b9e82dc495dc61be6e9a732afba72e685886/src/Http/Controllers/Controller.php#L428)

2018-04-16 20:09 UTC, marktopper commented
Sorry, we are closing issues for `v1.0` do to the release of `v1.1` that is out in a bit.
You are welcome to remake this for `v1.1`.

2018-04-16 20:09 UTC, closed without merging