Made the autoloading of migrations optional
thedevdojo/voyager pull request #3046
Opened 2018-04-23 22:01 UTC by JapSeyz

Adding the autoloading of the migrations blacklists certain classes even if the multilingual functions are not used.

I use Laravel Translation manager for a part of the application, and since I cannot change the name of the table/class from Voyager anymore, it throws an error because the "CreateTranslationsTable" class already exists inside your autoloaded vendor-migrations directory.

It breaks backwards compatibility of any app that already used that class-name, as I had to go research around to problem-solve why my migrations suddenly wouldn't run.

2018-04-24 01:50 UTC, fletch3555 requested changes

2018-04-24 01:50 UTC, fletch3555 commented on src/VoyagerServiceProvider.php
> +        if(config('voyager.load_migrations')) {
The default value should be true, else it's a breaking change, and breaks tests

2018-05-04 03:35 UTC, JapSeyz commented on src/VoyagerServiceProvider.php
> +        if(config('voyager.load_migrations')) {
Has been addressed in the newest commit

2018-05-04 03:37 UTC, JapSeyz commented
@fletch3555 I'll limit my composer.json to the version before this was introduced, could you ping me when/if this is merged, or I need to change anything else?

2018-08-07 20:17 UTC, fletch3555 commented
I'm not sure how I feel on this one.  On one hand, you can easily just copy the migration to your app and leave it blank (effectively nullifying it's behavior).  On the other, I'm not opposed to adding flexibility.  In either case, we'll either need the config added to the `voyager.php` config file, or noted in the docs.  Otherwise, nobody will know it exists.

2018-12-17 11:29 UTC, emptynick commented
This was implemented in https://github.com/the-control-group/voyager/pull/3584 and is configurable.
It was merged into 1.x

2018-12-17 11:29 UTC, closed without merging