Attempt to fix issue #3059
thedevdojo/voyager pull request #3060
Opened 2018-04-24 15:44 UTC by jannejava

If no image is uploaded the setting’s value become null and overwrites the previous value.

2018-05-02 17:36 UTC, emptynick requested changes

2018-05-02 17:36 UTC, emptynick commented on src/Http/Controllers/VoyagerSettingsController.php
Move your condition from line 91 here and use
`if ($setting->type == 'image' && $content == null)`
This makes everything else unnecessary.

2018-05-02 17:45 UTC, jannejava reviewed
Of course, I see what you mean. Should I do another pull request?

2018-05-02 18:04 UTC, emptynick commented
You just can push to your branch, it will update here automatically.

2018-05-02 20:37 UTC, jannejava commented
Did the update of the pull request work?

2018-05-03 17:20 UTC, fletch3555 commented
Yes it did.

Also, please try to avoid committing whitespace changes (new lines, indentation/spacing changes, etc).  All they do is make the diff harder to read, and make StyleCI revert them after this gets merged.  I understand some IDEs do this automatically, but you can just be more selective in what you commit (e.g. you can select specific lines instead of entire files).

2018-05-03 17:33 UTC, jannejava commented
Sorry for that! It must be php-cs-fixer, I have it set on PSR-2 but you are maybe using Symfony style? Anyway, I will try to disable it for this project. 

Do you have any idea if this would fix the disappearing images on the settings page? (it’s a little annoying, when the images disappear ;-))

2018-05-03 17:52 UTC, emptynick commented
Yep thats working

2018-05-03 17:52 UTC, emptynick approved these changes

2018-05-23 17:45 UTC, cyrildewit approved these changes
Looks good to me!

2018-05-30 15:34 UTC, merged