Patch user roles creation
thedevdojo/voyager pull request #3077
Opened 2018-04-27 10:37 UTC by xaviqv

- Laravel Version: 5.4
- Voyager Version: 1.1.0

In my migration list, users.id was not defined as unsigned integer, so the foreign key in user_roles table "user_id" could not be created due to this migration error:
![image](https://user-images.githubusercontent.com/25639840/39358773-89d6ac84-4a17-11e8-84d6-05b91f133d65.png)

2018-04-27 14:31 UTC, fletch3555 requested changes
This migration has existed for months and you're the first one claiming this doesn't work.  I agree that the types should match, but I'm thinking there's another issue at play.  It's possible your database is configured too strictly.  In either case, I can't approve this as-is.

2018-04-27 14:31 UTC, fletch3555 commented on migrations/2017_11_26_015000_create_user_roles_table.php
> +        Schema::table('users', function (Blueprint $table) {
We shouldn't be modifying the `users` table in a `create_user_roles_table` migration.  That will just confuse people

Also, we can't edit pre-existing migrations as upgrading users won't be able to run it.

2018-04-27 14:32 UTC, fletch3555 commented
What part of that error message indicates it's a field type conflict? All I see is an error saying you're trying to create a table with no fields

2018-05-02 08:22 UTC, xaviqv commented
@fletch3555 Maybe you're right with my database. I thought that It can be useful to anybody else that's getting the same error.

I got a foreign key error when I moved the foreign key creations to an additional Schema::table method in same migration that took me to this solution.

I comprehend what you say about modifying older migrations, but for anyone else that could get an error on this migration, modifying it is the only solution, rather than relying on a later one that won't execute.

Anyway, It will be okay for me to close and discard this change if in general usage it is wrong.

2019-02-26 23:00 UTC, closed without merging