Fix minor layout issue in responsive rtl
thedevdojo/voyager pull request #3130
Opened 2018-05-03 13:16 UTC by wp-src

2018-05-03 17:14 UTC, fletch3555 requested changes

2018-05-03 17:14 UTC, fletch3555 commented on publishable/assets/css/rtl.css
> +[dir="rtl"]  .voyager .navbar .navbar-nav .dropdown-menu, [dir="rtl"] .voyager .navbar.navbar-default .navbar-nav .dropdown-menu {
The second selector is not necessary here as it's a subset of the first (.navbar vs .navbar.navbar-default) and therefore adds no value.

2018-05-03 17:14 UTC, fletch3555 commented on publishable/assets/css/rtl.css
> +[dir="rtl"]  .voyager .navbar .navbar-nav li.dropdown.open .dropdown-menu, [dir="rtl"] .voyager .navbar.navbar-default .navbar-nav li.dropdown.open .dropdown-menu {
Same as above.

2018-05-03 17:15 UTC, fletch3555 commented
Please avoid closing one PR and open another just to add changes.  PRs are a live comparison of the two branches, so they will automatically update when you push new commits.

2018-05-03 17:31 UTC, fletch3555 requested changes

2018-05-03 17:31 UTC, fletch3555 commented on npm-debug.log
> +0 info it worked if it ends with ok
This file should not be committed.  Again, please be cognizant of what you're committing.

2018-05-03 17:33 UTC, wp-src commented
@fletch3555 Sry, i'm new on requesting pulls. i was created another branch and after that created another branch with better name!
Is it ok if i commit all changes to code or styles in this branch and current pr ?

2018-05-03 17:40 UTC, fletch3555 commented
No worries.  Don't worry about branch names (pick something somewhat reasonable, but there's no need to change it after it got this far).

For the other changes, you should limit pull requests to distinct functionality, and since a PR is only a single branch, you should limit your changes to distinct branches.  For example, if you're making a bunch of code-style/formatting/spelling/etc changes, then they can all go together in one branch/PR.  If you're fixing a bug in the BREAD system, and also adding a new language worth of translation files, then those should be 2 separate branches/PRs.  Make sense?

2018-05-03 17:47 UTC, fnaysee commented
OK got it.

2018-08-23 20:03 UTC, fletch3555 approved these changes

2018-08-24 20:37 UTC, fletch3555 commented
@wp-src, looks like you deleted your fork, so we're unable to merge this in.  If you'd like to recreate the PR, we'll be happy to get it merged in.

2019-02-21 09:42 UTC, emptynick commented
Closing.
If someone wants to recreate the changes made in this PR feel free to do so.

2019-02-21 09:42 UTC, closed without merging