Compass security fixes
thedevdojo/voyager pull request #3267
Opened 2018-06-01 10:25 UTC by jannejava

Attempt to fix the security issues in #3227 by escaping the arguments to prevent appending commands. Also, removing the ability to send in absolute paths in the log-viewer and only use the check if the file is present in the log-directory.

Fixes #3032 
Fixes #3227

2018-06-01 23:32 UTC, fletch3555 commented
Does this fix all of the issues in #3227?

2018-06-01 23:32 UTC, fletch3555 submitted a review, later dismissed

2018-06-03 14:28 UTC, jannejava commented
I hope so, at least on *nix environments. Wrote some tests to prove the case. Even if testing with Orchestral/TestBench and Artisan commands are not friends. Mocking base_path() seems not to be trivial.

2018-06-03 14:30 UTC, jannejava commented
I hope so. 

Saw that I made a mistake and escaping empty arguments, fixed this now.

Wrote some tests to prove the case. Even if testing with Orchestral and Artisan commands are not that easy.

2018-08-08 20:22 UTC, fletch3555 requested changes

2018-08-08 20:22 UTC, fletch3555 commented on src/Http/Controllers/VoyagerCompassController.php
> +                    $path = realpath(base_path('../../../../../../../'));
This path is a few levels too high and is causing TravisCI to fail.  What are you expecting the starting directory will be? What about the path to `artisan`?

Why not use the `Artisan` facade instead?

2018-08-09 07:47 UTC, jannejava commented on src/Http/Controllers/VoyagerCompassController.php
> +                    $path = realpath(base_path('../../../../../../../'));
I don't know why the facade is not used here. My guess is the challenge is how to parse and make an array of non-optional arguments from the input string, also knowing the parameters of a particular command. That's maybe the reason?  

Using `Artisan:call()` would be better I think. Laravel will then handle illegal calls to non-Artisan commands and options and prevent shell injections. 

´´´
    $exitCode = Artisan::call('email:send', [
        'user' => 1, '--queue' => 'default'
    ]);
´´´

Skipping non-optional all together is an option?

2018-08-09 15:25 UTC, emptynick commented on src/Http/Controllers/VoyagerCompassController.php
> +                    $path = realpath(base_path('../../../../../../../'));
I guess thats as simple as
```
$in = "--arg1=yes --arg2=no --arg3=whatever";

$parameter = [];
$arguments = explode('--', $in);

foreach ($arguments as $arg) {
    $arg = trim($arg);
    if ($arg != '') {
        $parts = explode('=', $arg);
        $parameter[$parts[0]] = $parts[1];
    }
}

dd($parameter);
```

Maybe there is a nicer way with Laravel Collections.

2018-08-09 20:42 UTC, jannejava commented on src/Http/Controllers/VoyagerCompassController.php
> +                    $path = realpath(base_path('../../../../../../../'));
That would work for most of the commands. But if you look at the signature for e.g. migrations which takes more than an option. 

```php
protected $signature = 'make:migration {name : The name of the migration.}'
```

To run this you must know that the arguments name is before to build the array. 

```php
    $exitCode = Artisan::call('make:migration', [
        'name' => 'the_name_of_migration'
    ]);
```

You cannot just send an array like this:

```php
    $exitCode = Artisan::call('make:migration', [
        'the_name_of_migration'
    ]);
```

2018-09-09 20:35 UTC, dexcell commented
this is not fixed yet?

2019-02-21 09:43 UTC, emptynick commented
Closing as superseeded by https://github.com/the-control-group/voyager/pull/3823

2019-02-21 09:43 UTC, closed without merging