Improve RTL version of login page
thedevdojo/voyager pull request #3306
Opened 2018-06-13 14:03 UTC by amirmasoud

2018-06-14 21:49 UTC, emptynick commented
I just changed your base-branch from `1.1` to `1.x` because the css file needs publishing. (And I by mistake merged 1.1 into your master)

By the way, cant you just [flip the image](https://www.w3schools.com/howto/howto_css_flip_image.asp)?

2018-06-15 07:50 UTC, amirmasoud commented
@emptynick I have tried it, it cause whole body to flip, background-color is set on body tag, for this solution I needed more changes to be done, I just did the easiest way.

2018-12-30 11:36 UTC, emptynick requested changes

2018-12-30 11:36 UTC, emptynick commented on resources/views/login.blade.php
> +            @if (config('voyager.multilingual.rtl'))
This config doesn't exist in 1.x anymore.
Please refer to this line:
https://github.com/the-control-group/voyager/blob/58a45466660c99bf010e0431e0ab6d9d5392a6cb/resources/views/master.blade.php#L2

2019-02-21 09:46 UTC, emptynick requested changes

2019-02-21 09:46 UTC, emptynick commented on resources/views/login.blade.php
> +            @if (config('voyager.multilingual.rtl'))
Changing to new RTL style
```suggestion
            @if (__('voyager::generic.is_rtl') == 'true')
```

2019-06-02 17:42 UTC, emptynick requested changes
I'm not really happy with having another image just so its mirrored.
In my opinion this can be done through CSS.

2019-07-28 19:15 UTC, emptynick commented
Closing as the fork was deleted.

2019-07-28 19:15 UTC, closed without merging