Where translation
thedevdojo/voyager pull request #3417
Opened 2018-07-24 19:48 UTC by reageek

Adds functionality to allow searching for translated values in fields. 

The primary use case I had was for this functionality was for finding translated content via slugs. 

class PageController extends Controller
{   
    
 ...
    /**
     * Display the specified page or 404.
     *
     * @param string $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {   
        $page = Page::whereTranslation( $this->locale, 'slug', $slug );
        abort_unless($page, 404);
        $page = $page->withTranslations($this->locales)->active()->first();
        return ($page->first()) ? $this->RenderView($this->_pageData($page)) : abort(404);
    }

2018-11-09 20:01 UTC, emptynick requested changes

2018-11-09 20:01 UTC, emptynick commented on src/Traits/Translatable.php
> +    public function scopeWhereTranslation(Builder $query, $locales, string $field, string $operator, string $value = null, bool $default = false){
Argument type declarations `string` and `bool` were introduced with PHP 7 but we still support 5.4, ref:
http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration
```suggestion
    public function scopeWhereTranslation(Builder $query, $locales, $field, $operator, $value = null, $default = false){
```

2018-11-09 20:01 UTC, emptynick commented on src/Traits/Translatable.php
> +    public static function whereTranslation( $locales, string $field, string $operator, string $value = null, bool $default = false )
Same as above
```suggestion
    public static function whereTranslation( $locales, $field, $operator, $value = null, $default = false )
```

2018-11-09 20:26 UTC, emptynick submitted a review, later dismissed

2018-11-09 20:26 UTC, emptynick commented on src/Traits/Translatable.php
> +        $table = ( isset($self->table) ) ? $self->table : studly_case( str_plural ( class_basename( $self ) ) ); //discern table name
`$self->getTable()` does this for you already
```suggestion
        $table = $self->getTable();
```

2018-11-13 12:07 UTC, emptynick commented
Sorry for being late. A few more things:
I think the locales-array should not be necessary, so if no locales are given, all are searched.
That would require to put `$locales` somewhere behind `$value`
Next, I think `$default` should be `true` by default.
So, in the end, something like
`whereTranslation($field, $operator, $value = null, $locales = null, $default = true)`

2018-11-20 16:45 UTC, reageek commented
> 
> 
> Sorry for being late. A few more things:
> I think the locales-array should not be necessary, so if no locales are given, all are searched.
> That would require to put `$locales` somewhere behind `$value`
> Next, I think `$default` should be `true` by default.
> So, in the end, something like
> `whereTranslation($field, $operator, $value = null, $locales = null, $default = true)`
> And for looping through the locales, you could simply use [whereIn](https://laravel.com/docs/collections#method-wherein) I think.

All sound like good ideas. I will look into them. When I have some downtime I will look at updating this.

2018-12-14 11:30 UTC, emptynick commented
I commited the stuff I suggested above and added some documentation.
@fletch3555 wanna take a look at the wording?

2018-12-14 13:20 UTC, reageek commented
Good changes/refactor. 

Sorry I just really have not had the time (end of the year crunch) to really finish this pr.

One thing that might be noting is in the documentation is that this function does currently override the scope of a query builder due to its static call nature on self. Might be worth putting in. 

To fix this line 304 needs to have a check to see if its statically called in a query builder and use self or the query builder instance.

2018-12-30 01:20 UTC, emptynick commented
Laravel does all this for you.
Tested both static and normal calls. Also I simplified the default-clause.
Now it looks good in my eyes. What do you think?

2018-12-30 01:34 UTC, emptynick submitted a review, later dismissed

2018-12-30 02:00 UTC, emptynick approved these changes

2019-01-02 19:51 UTC, fletch3555 approved these changes

2019-01-02 19:52 UTC, merged