added listener for bread delete for menu and permission removal
thedevdojo/voyager pull request #3621
Opened 2018-10-11 07:22 UTC by ntuple

**Delete** the **Menu** and **Permissions** associated with a **Bread** if the Bread is deleted.

2018-10-12 18:52 UTC, fletch3555 requested changes

2018-10-12 18:52 UTC, fletch3555 commented on src/Listeners/DeleteBreadMenuItem.php
> +        if (config('voyager.bread.add_menu_item') && file_exists(base_path('routes/web.php'))) {
What's the purpose of checking for the route file?

2018-10-12 18:52 UTC, fletch3555 commented on src/Listeners/DeleteBreadPermission.php
> +        if (config('voyager.bread.add_permission') && file_exists(base_path('routes/web.php'))) {
Again with the route file

2018-10-12 18:52 UTC, fletch3555 commented on src/Listeners/DeleteBreadPermission.php
> +            $role = Role::where('name', config('voyager.bread.default_role'))->firstOrFail();
None of this is necessary.  I'd say it's safe to assume the database is set up correctly with ONDELETE, and will delete the associated pivot table rows when the permissions themselves are deleted.

2018-10-12 18:52 UTC, fletch3555 commented on src/Listeners/DeleteBreadPermission.php
> +            $role->permissions()->detach($permissions);
You're not actually deleting the permissions anywhere, just removing them from the default user.  Instead, they should be deleted and removed from all roles (ideally automatically per my comment above, or manually if soft-delete is used)

2018-11-11 11:49 UTC, emptynick submitted a review, later dismissed

2018-11-11 11:49 UTC, emptynick commented on src/Listeners/DeleteBreadMenuItem.php
> +            $menuItem = MenuItem::where(['title' => $bread->dataType->display_name_plural]);
I think its more unique/safe to select the menu-item by the route.
```suggestion
            $menuItem = MenuItem::where('route', 'voyager.'.$bread->dataType->slug.'.index');
```

2018-12-01 02:12 UTC, fletch3555 approved these changes

2018-12-01 02:15 UTC, merged