fix relationship  browse.blade.php
thedevdojo/voyager pull request #3660
Opened 2018-10-20 15:17 UTC by KarimQaderi

fix relationship

2018-10-20 15:50 UTC, emptynick requested changes
Same as
https://github.com/the-control-group/voyager/pull/3661#pullrequestreview-166753414

2018-10-20 16:42 UTC, emptynick approved these changes

2018-10-20 16:42 UTC, emptynick commented
Thats better, and fixes https://github.com/the-control-group/voyager/issues/3659

2018-10-21 15:45 UTC, merged

2018-10-28 17:05 UTC, Xoshbin commented
Is this bug fixed? Because I still have this issue, I can't see relationship dropdowns in the breads!