Customize admin favicon using admin.icon_image setting
thedevdojo/voyager pull request #4051
Opened 2019-03-29 14:23 UTC by olegtsoy

Adding possibility to change favicon using admin.icon_image setting

2019-04-01 09:57 UTC, MrCrayon requested changes
I think in this case a one line solution might be enough:
```diff
-<link rel="shortcut icon" href="{{ voyager_asset('images/logo-icon.png') }}" type="image/x-icon">
+<link rel="shortcut icon" href="{{ Voyager::setting('admin.icon_image') ? Voyager::image(Voyager::setting('admin.icon_image')) : voyager_asset('images/logo-icon.png') }}" type="image/x-icon">
```
But if you want to keep the if else for clarity, to not repeat html, I would do something like this:
```blade
@php
if (Voyager::setting('admin.icon_image')) {
    $admin_favicon = Voyager::image(Voyager::setting('admin.icon_image'));
} else {
    $admin_favicon = voyager_asset('images/logo-icon.png');
}
@endphp
<link rel="shortcut icon" href="{{ $admin_favicon }}" type="image/x-icon">
```

2019-04-01 10:32 UTC, olegtsoy commented
@MrCrayon thanks for your comment, i used the same code in my commit as [there](https://github.com/the-control-group/voyager/blob/e3ab444f365eaf6ef140004737a4fe6aa24c6b3e/resources/views/master.blade.php#L58-L63) for unified code styling

2019-04-01 11:51 UTC, MrCrayon submitted a review, later dismissed
@olegtsoy I saw about your choice for code styling, it makes sense.

Works for me.

2019-04-02 09:54 UTC, emptynick commented
I'm not a hundred percent sure that this is compatible with
https://github.com/the-control-group/voyager/blob/317ce0f2014b08ea4f0f3ead0f973f1c952f642c/resources/views/login.blade.php#L50-L55
What happens if you upload a .ico file? Also, I think some browser don't directly accept a PNG as a favicon (IE for example)

2019-04-03 10:38 UTC, MrCrayon commented
According to https://en.wikipedia.org/wiki/Favicon PNG and ICO are supported on all modern browsers, including IE11.
If someone is still using older IE versions not seeing bookmark icon might be the last of their problems :laughing:

2019-04-05 10:50 UTC, emptynick commented
Its more about ` type="image/x-icon"`.
Uploading a PNG might (not sure) result in errors/notices in the console.
Can't we just change it to `image/png` and only use `image/x-icon` for the default .ico file?

2019-05-01 19:05 UTC, fletch3555 requested changes

2019-05-01 19:05 UTC, fletch3555 commented on resources/views/master.blade.php
> +        <link rel="shortcut icon" href="{{ voyager_asset('images/logo-icon.png') }}" type="image/x-icon">
I agree with @emptynick.  Please change to `type="image/png"`

2019-06-02 17:15 UTC, emptynick approved these changes

2019-06-02 18:07 UTC, emptynick approved these changes

2019-06-02 18:08 UTC, merged