Update Dimmer i.e. Widget layout and procedures
thedevdojo/voyager pull request #4559
Opened 2019-11-14 00:47 UTC by Spraynard

This update contains two changes to two different files.

I had an issue similar to Issue #3185 and was able to implement a solution that works along with the current voyager configuration but allow for more than three widgets to be on the dashboard window.

This is what the dashboard window looks like with 1 - 3 Widgets

![voyager_widgets_1](https://user-images.githubusercontent.com/17299952/68816922-05a2ea00-064e-11ea-99ca-f82be0b0b618.png)

This is what the dashboard window looks like with 5 widgets

![voyager_widgets_2](https://user-images.githubusercontent.com/17299952/68817001-4e5aa300-064e-11ea-9347-aa2aaf081afe.png)

Please let me know if there is any more information needed

2019-11-20 10:52 UTC, MrCrayon requested changes
Except Test everything else looks good. :+1:

2019-11-20 10:52 UTC, MrCrayon commented on tests/Unit/VoyagerTest.php
> +    public function testEachDimmerGroupHasAMaxAmountOfThreeDimmers()
If you want to test that Group has max amount of three Dimmers you should set 3 dimmers in config and assert equals 1, then set 4 dimmers and assert equals 2.

Right now you could have 4 dimmers in the first group without error.

2019-11-20 18:24 UTC, Spraynard commented on tests/Unit/VoyagerTest.php
> +    public function testEachDimmerGroupHasAMaxAmountOfThreeDimmers()
Thank you for the guidance. I'll commit an updated VoyagerTest.php

2019-11-21 02:54 UTC, MrCrayon requested changes
I think you can remove the first test.

2019-11-21 02:54 UTC, MrCrayon commented on tests/Unit/VoyagerTest.php
> +        $this->assertEquals(3, $dimmers[0]->count());
This assertion proves what you were trying to prove in the previous test, so I think the other one can be removed.

2019-11-21 02:59 UTC, MrCrayon requested changes
This test can be removed.

2019-11-21 02:59 UTC, MrCrayon commented on tests/Unit/VoyagerTest.php
> +    public function testDimmerCollectionContainsThreeDimmersMax()
How can you test that collection contains three dimmers max if you are only passing three? :thinking:

2019-11-21 03:52 UTC, MrCrayon approved these changes
Looks good, thanks for this PR

2019-11-21 04:59 UTC, Spraynard commented
Thank you very much for the help as well. It's much appreciated.

2020-01-15 12:11 UTC, merged