Fix of BUG
thedevdojo/voyager pull request #4782
Opened 2020-02-26 07:58 UTC by georak

Call to a member function getTranslatedAttribute() on null {"userId":4,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getTranslatedAttribute() on null at /app/vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php:55

2020-03-02 07:07 UTC, JackShev submitted a review, later dismissed

2020-03-10 21:29 UTC, emptynick requested changes

2020-03-10 21:29 UTC, emptynick commented on src/Http/Controllers/VoyagerBaseController.php
>                  $searchNames[$value] = $displayName ?: ucwords(str_replace('_', ' ', $value));
I'm not really a big fan of those one-line conditions so I suggest doing something like:

```suggestion
                $displayName = ucwords(str_replace('_', ' ', $value));
                if ($field !== null) {
                    $displayName = $field->getTranslatedAttribute('display_name');
                }
                $searchNames[$value] = $displayName;
```

2020-04-05 13:02 UTC, emptynick approved these changes

2020-04-05 13:10 UTC, merged