Update voyager.php
thedevdojo/voyager pull request #5302
Opened 2021-04-29 16:54 UTC by mepsd

in laravel 8 default namespace is App\Model\ so it is better uncomment in default and show the correct route while creating bread to table

2021-04-29 17:02 UTC, fletch3555 commented
It's commented out so it won't affect anything.  If you want to change it, I don't have any concerns, but please leave it commented in the PR

2021-04-30 05:49 UTC, mepsd commented
Okay Thanks, i just saw this relative path error while creating bread so i think to update that.

2021-04-30 15:36 UTC, emptynick approved these changes

2021-04-30 15:37 UTC, emptynick requested changes, later dismissed
Please also change voyager_dummy.php

2021-05-01 08:56 UTC, emptynick approved these changes

2021-05-01 09:07 UTC, merged