Custom field views for specific action
thedevdojo/voyager pull request #5454
Opened 2021-09-29 22:50 UTC by jimmysp

Hi, first of all, this is my first PR, hope I got it right. 
I would like to improve the custom field views, having options for each separate action. I also made an edit in the documentation section, the custom views can be set like this:
{
    "view_browse": "my_browse_view",
    "view_read": "my_read_view",
    "view_add": "my_add_view",
    "view_edit": "my_edit_view",
    "view_order": "my_order_view"
}

2021-11-10 11:54 UTC, emptynick requested changes, later dismissed

2021-11-10 11:54 UTC, emptynick commented on docs/bread/formfields/introduction.md
> -Formfields are the hearth of Voyagers BREAD-system.
This tells the markdown parser to add a line-break here which we want.
Please revert those changes (same for the other lines below)

2021-11-10 16:17 UTC, jimmysp commented
Ok, I restored the whitespaces with a new commit.

2021-11-10 20:26 UTC, emptynick commented
I think for consistency it would be great to pass `$view` as well.
This way you could also have the same view for browse and read for example, which are very similar from code perspective.

2021-11-10 22:20 UTC, jimmysp commented
Indeed, it could be useful to use the same view for similar actions... I pushed a new commit for this.

2022-02-18 10:34 UTC, emptynick approved these changes

2022-02-18 10:43 UTC, merged